services:
  grafana:
    image: grafana/grafana:11.0.0-preview
    ports:
      - 3333:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_PATHS_PROVISIONING=/var/lib/grafana/provisioning
    volumes:
      - ./provisioning:/var/lib/grafana/provisioning
