scrape_configs:
  - job_name: 'space'
    metrics_path: /space
    static_configs:
      - targets:
          - 127.0.0.1:9999
# END OMIT
  - job_name: 'space_exporter'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 127.0.0.1:9999
